-- Schema operacional mínimo, porém representativo, para as telas principais.
-- Os IDs e campos seguem os contratos consumidos pelo cliente Supabase atual.

CREATE TABLE IF NOT EXISTS public.omnia_statuses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL UNIQUE,
  color TEXT NOT NULL DEFAULT '#2563EB',
  order_position INTEGER NOT NULL DEFAULT 0,
  is_default BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.omnia_ticket_statuses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL UNIQUE,
  color TEXT NOT NULL DEFAULT '#2563EB',
  order_position INTEGER NOT NULL DEFAULT 0,
  is_default BOOLEAN NOT NULL DEFAULT false,
  is_final BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.omnia_admissao_statuses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL UNIQUE,
  color TEXT NOT NULL DEFAULT '#2563EB',
  order_position INTEGER NOT NULL DEFAULT 0,
  is_default BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.omnia_rescisao_statuses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL UNIQUE,
  color TEXT NOT NULL DEFAULT '#2563EB',
  order_position INTEGER NOT NULL DEFAULT 0,
  is_default BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.omnia_atas (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  description TEXT,
  meeting_date DATE,
  status_id UUID NOT NULL REFERENCES public.omnia_statuses(id),
  condominium_id UUID REFERENCES public.omnia_condominiums(id),
  secretary_id UUID REFERENCES public.omnia_users(id),
  responsible_id UUID REFERENCES public.omnia_users(id),
  created_by UUID REFERENCES public.omnia_users(id),
  ticket TEXT,
  tags TEXT[] DEFAULT ARRAY[]::TEXT[],
  comment_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.omnia_comments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ata_id UUID NOT NULL REFERENCES public.omnia_atas(id) ON DELETE CASCADE,
  author_id UUID NOT NULL REFERENCES public.omnia_users(id),
  created_by UUID REFERENCES public.omnia_users(id),
  body TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.omnia_attachments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ata_id UUID REFERENCES public.omnia_atas(id) ON DELETE CASCADE,
  comment_id UUID REFERENCES public.omnia_comments(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  url TEXT NOT NULL,
  size_kb NUMERIC,
  mime_type TEXT,
  uploaded_by UUID REFERENCES public.omnia_users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.omnia_ticket_recurrences (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  description TEXT,
  status_id UUID NOT NULL REFERENCES public.omnia_ticket_statuses(id),
  priority TEXT NOT NULL DEFAULT 'MEDIA',
  frequency TEXT NOT NULL DEFAULT 'WEEKLY',
  interval INTEGER NOT NULL DEFAULT 1,
  start_date DATE NOT NULL DEFAULT CURRENT_DATE,
  end_type TEXT NOT NULL DEFAULT 'NEVER',
  end_date DATE,
  occurrence_limit INTEGER,
  generated_occurrences INTEGER NOT NULL DEFAULT 0,
  next_occurrence_date DATE,
  is_active BOOLEAN NOT NULL DEFAULT true,
  is_private BOOLEAN NOT NULL DEFAULT false,
  tags TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  assigned_to UUID REFERENCES public.omnia_users(id),
  created_by UUID REFERENCES public.omnia_users(id),
  template_ticket_id UUID,
  ticket_octa TEXT,
  oportunidade_id UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.omnia_tickets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  title TEXT NOT NULL,
  description TEXT,
  status_id UUID NOT NULL REFERENCES public.omnia_ticket_statuses(id),
  priority TEXT NOT NULL DEFAULT 'MEDIA',
  due_date DATE,
  assigned_to UUID REFERENCES public.omnia_users(id),
  created_by UUID REFERENCES public.omnia_users(id),
  is_private BOOLEAN NOT NULL DEFAULT false,
  tags TEXT[] DEFAULT ARRAY[]::TEXT[],
  comment_count INTEGER NOT NULL DEFAULT 0,
  attachment_count INTEGER NOT NULL DEFAULT 0,
  recurrence_id UUID REFERENCES public.omnia_ticket_recurrences(id),
  recurrence_occurrence INTEGER,
  ticket_octa TEXT,
  oportunidade_id UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'omnia_ticket_recurrences_template_ticket_id_fkey'
      AND conrelid = 'public.omnia_ticket_recurrences'::regclass
  ) THEN
    ALTER TABLE public.omnia_ticket_recurrences
      ADD CONSTRAINT omnia_ticket_recurrences_template_ticket_id_fkey
      FOREIGN KEY (template_ticket_id) REFERENCES public.omnia_tickets(id);
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.omnia_ticket_comments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id UUID NOT NULL REFERENCES public.omnia_tickets(id) ON DELETE CASCADE,
  author_id UUID NOT NULL REFERENCES public.omnia_users(id),
  created_by UUID REFERENCES public.omnia_users(id),
  body TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.omnia_ticket_attachments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id UUID NOT NULL REFERENCES public.omnia_tickets(id) ON DELETE CASCADE,
  comment_id UUID REFERENCES public.omnia_ticket_comments(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  url TEXT NOT NULL,
  size_kb NUMERIC,
  mime_type TEXT,
  uploaded_by UUID REFERENCES public.omnia_users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.omnia_admissoes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  title TEXT NOT NULL,
  description TEXT,
  status_id UUID NOT NULL REFERENCES public.omnia_admissao_statuses(id),
  priority TEXT NOT NULL DEFAULT 'MEDIA',
  due_date DATE,
  assigned_to UUID REFERENCES public.omnia_users(id),
  created_by UUID REFERENCES public.omnia_users(id),
  is_private BOOLEAN NOT NULL DEFAULT false,
  tags TEXT[] DEFAULT ARRAY[]::TEXT[],
  comment_count INTEGER NOT NULL DEFAULT 0,
  attachment_count INTEGER NOT NULL DEFAULT 0,
  ticket_octa TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.omnia_rescisoes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  title TEXT NOT NULL,
  description TEXT,
  status_id UUID NOT NULL CONSTRAINT omnia_demissoes_status_id_fkey REFERENCES public.omnia_rescisao_statuses(id),
  priority TEXT NOT NULL DEFAULT 'MEDIA',
  due_date DATE,
  assigned_to UUID CONSTRAINT omnia_demissoes_assigned_to_fkey REFERENCES public.omnia_users(id),
  created_by UUID CONSTRAINT omnia_demissoes_created_by_fkey REFERENCES public.omnia_users(id),
  is_private BOOLEAN NOT NULL DEFAULT false,
  tags TEXT[] DEFAULT ARRAY[]::TEXT[],
  comment_count INTEGER NOT NULL DEFAULT 0,
  attachment_count INTEGER NOT NULL DEFAULT 0,
  ticket_octa TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'omnia_rescisoes_assigned_to_fkey' AND conrelid = 'public.omnia_rescisoes'::regclass)
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'omnia_demissoes_assigned_to_fkey' AND conrelid = 'public.omnia_rescisoes'::regclass) THEN
    ALTER TABLE public.omnia_rescisoes RENAME CONSTRAINT omnia_rescisoes_assigned_to_fkey TO omnia_demissoes_assigned_to_fkey;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'omnia_rescisoes_created_by_fkey' AND conrelid = 'public.omnia_rescisoes'::regclass)
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'omnia_demissoes_created_by_fkey' AND conrelid = 'public.omnia_rescisoes'::regclass) THEN
    ALTER TABLE public.omnia_rescisoes RENAME CONSTRAINT omnia_rescisoes_created_by_fkey TO omnia_demissoes_created_by_fkey;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'omnia_rescisoes_status_id_fkey' AND conrelid = 'public.omnia_rescisoes'::regclass)
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'omnia_demissoes_status_id_fkey' AND conrelid = 'public.omnia_rescisoes'::regclass) THEN
    ALTER TABLE public.omnia_rescisoes RENAME CONSTRAINT omnia_rescisoes_status_id_fkey TO omnia_demissoes_status_id_fkey;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.omnia_balancete_csv_import_batches (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  original_filename TEXT NOT NULL,
  total_rows INTEGER NOT NULL DEFAULT 0,
  created_count INTEGER NOT NULL DEFAULT 0,
  updated_count INTEGER NOT NULL DEFAULT 0,
  ignored_count INTEGER NOT NULL DEFAULT 0,
  not_matched_count INTEGER NOT NULL DEFAULT 0,
  details JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_by UUID REFERENCES public.omnia_users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.omnia_protocolos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  protocol_number TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.omnia_balancetes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  condominium_id UUID NOT NULL REFERENCES public.omnia_condominiums(id),
  competencia TEXT NOT NULL,
  volumes INTEGER NOT NULL DEFAULT 1,
  observations TEXT,
  status TEXT NOT NULL DEFAULT 'RECEBIDO',
  received_at TIMESTAMPTZ,
  sent_at TIMESTAMPTZ,
  digital_prepared_at TIMESTAMPTZ,
  csv_import_batch_id UUID REFERENCES public.omnia_balancete_csv_import_batches(id),
  protocolo_id UUID REFERENCES public.omnia_protocolos(id),
  created_by UUID NOT NULL REFERENCES public.omnia_users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (condominium_id, competencia)
);

CREATE TABLE IF NOT EXISTS public.omnia_balancete_attachments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  balancete_id UUID NOT NULL REFERENCES public.omnia_balancetes(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  url TEXT NOT NULL,
  mime_type TEXT,
  size_kb NUMERIC,
  uploaded_by UUID REFERENCES public.omnia_users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

DO $$
DECLARE table_name TEXT;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'omnia_statuses', 'omnia_ticket_statuses', 'omnia_admissao_statuses',
    'omnia_rescisao_statuses', 'omnia_atas', 'omnia_comments', 'omnia_attachments',
    'omnia_ticket_recurrences', 'omnia_tickets', 'omnia_ticket_comments',
    'omnia_ticket_attachments', 'omnia_admissoes', 'omnia_rescisoes',
    'omnia_balancete_csv_import_batches', 'omnia_protocolos', 'omnia_balancetes',
    'omnia_balancete_attachments'
  ] LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', table_name);
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', 'Authenticated users can read local data', table_name);
    EXECUTE format('CREATE POLICY %I ON public.%I FOR ALL TO authenticated USING (true) WITH CHECK (true)', 'Authenticated users can read local data', table_name);
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON public.%I TO authenticated', table_name);
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON public.%I TO service_role', table_name);
  END LOOP;
END $$;
