// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { logger } from '../../lib/logging';


// Check if running in browser
const isBrowser = typeof window !== 'undefined';

// Storage-safe wrapper for localStorage with fallback to in-memory storage
const createSafeStorage = () => {
  const memoryStorage = new Map<string, string>();
  
  return {
    getItem: (key: string): string | null => {
      if (!isBrowser) {
        return memoryStorage.get(key) || null;
      }
      try {
        return localStorage.getItem(key);
      } catch {
        return memoryStorage.get(key) || null;
      }
    },
    setItem: (key: string, value: string): void => {
      if (!isBrowser) {
        memoryStorage.set(key, value);
        return;
      }
      try {
        localStorage.setItem(key, value);
      } catch {
        memoryStorage.set(key, value);
      }
    },
    removeItem: (key: string): void => {
      if (!isBrowser) {
        memoryStorage.delete(key);
        return;
      }
      try {
        localStorage.removeItem(key);
      } catch {
        memoryStorage.delete(key);
      }
    }
  };
};

// Supabase project configuration — values come from .env.local (dev) or Vercel env vars (prod)
const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'Missing Supabase environment variables. ' +
    'Set NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY in .env.local (dev) or Vercel dashboard (prod).'
  );
}

export const SUPABASE_ANON_KEY: string = SUPABASE_PUBLISHABLE_KEY!;
// Re-export as typed string (validated above)
const _SUPABASE_URL: string = SUPABASE_URL!;
export { _SUPABASE_URL as SUPABASE_URL };

if (isBrowser) {
  logger.debug('[SUPABASE] Initializing client with URL:', SUPABASE_URL);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
  auth: {
    storage: createSafeStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});