// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { logger } from '../../lib/logging';


// Storage-safe wrapper for localStorage with fallback to in-memory storage
const createSafeStorage = () => {
  const memoryStorage = new Map<string, string>();
  
  return {
    getItem: (key: string): string | null => {
      try {
        return localStorage.getItem(key);
      } catch (error) {
        logger.warn('[SUPABASE] localStorage not available, using memory storage:', error);
        return memoryStorage.get(key) || null;
      }
    },
    setItem: (key: string, value: string): void => {
      try {
        localStorage.setItem(key, value);
      } catch (error) {
        logger.warn('[SUPABASE] localStorage not available, using memory storage:', error);
        memoryStorage.set(key, value);
      }
    },
    removeItem: (key: string): void => {
      try {
        localStorage.removeItem(key);
      } catch (error) {
        logger.warn('[SUPABASE] localStorage not available, using memory storage:', error);
        memoryStorage.delete(key);
      }
    }
  };
};

// Supabase project configuration
const SUPABASE_URL = "https://elmxwvimjxcswjbrzznq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsbXh3dmltanhjc3dqYnJ6em5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMDQ1NjIsImV4cCI6MjA3MDc4MDU2Mn0.nkapAcvAok4QNPSlLwkfTEbbj90nXJf3gRvBZauMfqI";

logger.info('[SUPABASE] Initializing client with URL:', SUPABASE_URL);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: createSafeStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});